### ISSUE TITLE
Possible Security Risk: nsec appears to have been retained after Primal App deletion on iOS.

### ISSUE THREAD

**Issue by swbratcher** [PrimalHQ/primal-ios-app#140]
### Description
I was testing another issue. To make sure that issue wasn't caused by a persistent app/data state I deleted the Primal app from my device. I installed the Primal iOS app again from the App Store. Then, upon launching the app, I was surprised to be already logged in with my `nsec`.

### Steps to reproduce
Log into app.
Delete app and data.
Install app. 
Open app.
Successfully reproduced if your logged in state has persisted.

### Expected Behavior
I would have expected to have to log back in due to App deletion clearing my nsec upon Delete App completion. 

### Environment
iPhone 15 Pro (MTU53LL/A)
Fresh upgrade to iOS 18.1.1
Fresh re-install of Primal v2.0.114
Fresh reboot of device after delete/install of Primal App

### Additional Behavior Notes
In the "Delete App" dialogue upon deletion of the Primal App from iOS, the options are given to "Delete App", "Remove from Home Screen", and "Cancel". For this issue to occur I did select Delete App, so it was not expected that any data would persist related to the application. I would however, expect data to persist, which could include session key retention, if I had selected "Remove from Home Screen".

**Comment by amunrarara** [comment]
I can confirm reproducibility on my device.

iOS 18.1.1
iPhone 12 Pro

**Comment by PavleKreator** [comment]
This is not a bug, and it's not a security issue. When you select delete app, the app code doesn't know the app is being deleted and no app code is being executed.

Because we are storing the nsec securely in apple keychain, it doesn't get deleted when the app gets deleted, but it is stored as securely as any other app login info that is stored in apple keychain. 

There is no way to automatically delete keychain data when the app is being deleted, that is handled by the system, and in some earlier versions of iOS it was being automatically deleted.

If you want the keychain to be removed from the device, just log out of the app before deleting it.

**Comment by PavleKreator** [comment]
There is no trigger to perform code when the app is deleted from the device. Access to the keychain is dependant on the provisioning profile that is used to sign the application. Therefore no other applications would be able to access this information in the keychain.
