### ISSUE TITLE
Reply UI gets stuck when using the reply text box

### ISSUE THREAD

**Issue by MarkoBraticevic** [PrimalHQ/primal-ios-app#69]
This issue only affects some users.

### Repro steps:
-Click on a post
-Select the reply text box (don't select the reply action button) 
-Type out a message 
-Press the reply button to post your reply

### Expected Behavior:
-Letters are displayed in the text field when typing 
-Reply is posted when clicking reply

### Actual Behavior:
-Letters are not displaying in the text field when typing on the keyboard
-Reply button does not post their message 

### Additional Context
One user provided a video example of their issue: https://primal.net/thread/note125t525rvkr7jqtgqfh2m5dlu29chk4jfsmsgcar0v0qnev49ljhsrkazqh

**Comment by walmer-bolfet** [comment]
I am having a similar problem with the Primal TestFlight iOS app with both Posting events and Replying to events.  It seems I can type my note, but the buttons to post hang and nothing happens with it.  I don’t know how to gather additional information.  
No problems with the desktop app.

**Comment by PavleKreator** [comment]
Uploading Simulator Screen Recording - iPhone 14 Plus - 2023-07-23 at 16.43.15.mp4…

The only way I could reproduce this is by using the emoji keyboard, and it seems like it's a system bug, because 90% of the time when selecting an emoji you stay in the emoji keyboard, but sometimes when selecting an emoji the system will automatically change to the text keyboard and enter into a bugged state. At that point the app is no longer receiving keyboard messages from the system so there is nothing we can do, as it's a system bug. See attached video.

I implemented a workaround for the next version.
